% Options for packages loaded elsewhere
\PassOptionsToPackage{unicode}{hyperref}
\PassOptionsToPackage{hyphens}{url}
%
\documentclass[
]{book}
\usepackage{amsmath,amssymb}
\usepackage{lmodern}
\usepackage{iftex}
\ifPDFTeX
  \usepackage[T1]{fontenc}
  \usepackage[utf8]{inputenc}
  \usepackage{textcomp} % provide euro and other symbols
\else % if luatex or xetex
  \usepackage{unicode-math}
  \defaultfontfeatures{Scale=MatchLowercase}
  \defaultfontfeatures[\rmfamily]{Ligatures=TeX,Scale=1}
\fi
% Use upquote if available, for straight quotes in verbatim environments
\IfFileExists{upquote.sty}{\usepackage{upquote}}{}
\IfFileExists{microtype.sty}{% use microtype if available
  \usepackage[]{microtype}
  \UseMicrotypeSet[protrusion]{basicmath} % disable protrusion for tt fonts
}{}
\makeatletter
\@ifundefined{KOMAClassName}{% if non-KOMA class
  \IfFileExists{parskip.sty}{%
    \usepackage{parskip}
  }{% else
    \setlength{\parindent}{0pt}
    \setlength{\parskip}{6pt plus 2pt minus 1pt}}
}{% if KOMA class
  \KOMAoptions{parskip=half}}
\makeatother
\usepackage{xcolor}
\usepackage{color}
\usepackage{fancyvrb}
\newcommand{\VerbBar}{|}
\newcommand{\VERB}{\Verb[commandchars=\\\{\}]}
\DefineVerbatimEnvironment{Highlighting}{Verbatim}{commandchars=\\\{\}}
% Add ',fontsize=\small' for more characters per line
\usepackage{framed}
\definecolor{shadecolor}{RGB}{248,248,248}
\newenvironment{Shaded}{\begin{snugshade}}{\end{snugshade}}
\newcommand{\AlertTok}[1]{\textcolor[rgb]{0.94,0.16,0.16}{#1}}
\newcommand{\AnnotationTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textbf{\textit{#1}}}}
\newcommand{\AttributeTok}[1]{\textcolor[rgb]{0.77,0.63,0.00}{#1}}
\newcommand{\BaseNTok}[1]{\textcolor[rgb]{0.00,0.00,0.81}{#1}}
\newcommand{\BuiltInTok}[1]{#1}
\newcommand{\CharTok}[1]{\textcolor[rgb]{0.31,0.60,0.02}{#1}}
\newcommand{\CommentTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textit{#1}}}
\newcommand{\CommentVarTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textbf{\textit{#1}}}}
\newcommand{\ConstantTok}[1]{\textcolor[rgb]{0.00,0.00,0.00}{#1}}
\newcommand{\ControlFlowTok}[1]{\textcolor[rgb]{0.13,0.29,0.53}{\textbf{#1}}}
\newcommand{\DataTypeTok}[1]{\textcolor[rgb]{0.13,0.29,0.53}{#1}}
\newcommand{\DecValTok}[1]{\textcolor[rgb]{0.00,0.00,0.81}{#1}}
\newcommand{\DocumentationTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textbf{\textit{#1}}}}
\newcommand{\ErrorTok}[1]{\textcolor[rgb]{0.64,0.00,0.00}{\textbf{#1}}}
\newcommand{\ExtensionTok}[1]{#1}
\newcommand{\FloatTok}[1]{\textcolor[rgb]{0.00,0.00,0.81}{#1}}
\newcommand{\FunctionTok}[1]{\textcolor[rgb]{0.00,0.00,0.00}{#1}}
\newcommand{\ImportTok}[1]{#1}
\newcommand{\InformationTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textbf{\textit{#1}}}}
\newcommand{\KeywordTok}[1]{\textcolor[rgb]{0.13,0.29,0.53}{\textbf{#1}}}
\newcommand{\NormalTok}[1]{#1}
\newcommand{\OperatorTok}[1]{\textcolor[rgb]{0.81,0.36,0.00}{\textbf{#1}}}
\newcommand{\OtherTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{#1}}
\newcommand{\PreprocessorTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textit{#1}}}
\newcommand{\RegionMarkerTok}[1]{#1}
\newcommand{\SpecialCharTok}[1]{\textcolor[rgb]{0.00,0.00,0.00}{#1}}
\newcommand{\SpecialStringTok}[1]{\textcolor[rgb]{0.31,0.60,0.02}{#1}}
\newcommand{\StringTok}[1]{\textcolor[rgb]{0.31,0.60,0.02}{#1}}
\newcommand{\VariableTok}[1]{\textcolor[rgb]{0.00,0.00,0.00}{#1}}
\newcommand{\VerbatimStringTok}[1]{\textcolor[rgb]{0.31,0.60,0.02}{#1}}
\newcommand{\WarningTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textbf{\textit{#1}}}}
\usepackage{longtable,booktabs,array}
\usepackage{calc} % for calculating minipage widths
% Correct order of tables after \paragraph or \subparagraph
\usepackage{etoolbox}
\makeatletter
\patchcmd\longtable{\par}{\if@noskipsec\mbox{}\fi\par}{}{}
\makeatother
% Allow footnotes in longtable head/foot
\IfFileExists{footnotehyper.sty}{\usepackage{footnotehyper}}{\usepackage{footnote}}
\makesavenoteenv{longtable}
\usepackage{graphicx}
\makeatletter
\def\maxwidth{\ifdim\Gin@nat@width>\linewidth\linewidth\else\Gin@nat@width\fi}
\def\maxheight{\ifdim\Gin@nat@height>\textheight\textheight\else\Gin@nat@height\fi}
\makeatother
% Scale images if necessary, so that they will not overflow the page
% margins by default, and it is still possible to overwrite the defaults
% using explicit options in \includegraphics[width, height, ...]{}
\setkeys{Gin}{width=\maxwidth,height=\maxheight,keepaspectratio}
% Set default figure placement to htbp
\makeatletter
\def\fps@figure{htbp}
\makeatother
\setlength{\emergencystretch}{3em} % prevent overfull lines
\providecommand{\tightlist}{%
  \setlength{\itemsep}{0pt}\setlength{\parskip}{0pt}}
\setcounter{secnumdepth}{5}
\usepackage{booktabs}
\ifLuaTeX
  \usepackage{selnolig}  % disable illegal ligatures
\fi
\usepackage[]{natbib}
\bibliographystyle{apalike}
\IfFileExists{bookmark.sty}{\usepackage{bookmark}}{\usepackage{hyperref}}
\IfFileExists{xurl.sty}{\usepackage{xurl}}{} % add URL line breaks if available
\urlstyle{same} % disable monospaced font for URLs
\hypersetup{
  pdftitle={Stat 120},
  pdfauthor={Deepak Bastola},
  hidelinks,
  pdfcreator={LaTeX via pandoc}}

\title{Stat 120}
\author{Deepak Bastola}
\date{2023-01-11}

\begin{document}
\maketitle

{
\setcounter{tocdepth}{1}
\tableofcontents
}
\hypertarget{about}{%
\chapter*{About}\label{about}}
\addcontentsline{toc}{chapter}{About}

This is a \emph{sample} book written in \textbf{Markdown} to guide STAT 120 students interactively explore various class activities and projects in R.

\hypertarget{class-activity-1}{%
\chapter{Class Activity 1}\label{class-activity-1}}

\hypertarget{your-turn-1}{%
\section{Your Turn 1}\label{your-turn-1}}

\begin{center}\rule{0.5\linewidth}{0.5pt}\end{center}

\begin{enumerate}
\def\labelenumi{\alph{enumi}.}
\tightlist
\item
  Run the following chunk. Comment on the output.
\end{enumerate}

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{example\_data }\OtherTok{=} \FunctionTok{data.frame}\NormalTok{(}\AttributeTok{ID =} \FunctionTok{c}\NormalTok{(}\DecValTok{1}\NormalTok{, }\DecValTok{2}\NormalTok{, }\DecValTok{3}\NormalTok{, }\DecValTok{4}\NormalTok{, }\DecValTok{5}\NormalTok{, }\DecValTok{6}\NormalTok{, }\DecValTok{7}\NormalTok{, }\DecValTok{8}\NormalTok{, }\DecValTok{9}\NormalTok{, }\DecValTok{10}\NormalTok{),}
                          \AttributeTok{Greeting =} \FunctionTok{c}\NormalTok{(}\FunctionTok{rep}\NormalTok{(}\StringTok{"Hello"}\NormalTok{, }\DecValTok{5}\NormalTok{), }\FunctionTok{rep}\NormalTok{(}\StringTok{"Goodbye"}\NormalTok{,}\DecValTok{5}\NormalTok{)),}
                          \AttributeTok{Male =} \FunctionTok{rep}\NormalTok{(}\FunctionTok{c}\NormalTok{(}\ConstantTok{TRUE}\NormalTok{, }\ConstantTok{FALSE}\NormalTok{), }\DecValTok{5}\NormalTok{),}
                          \AttributeTok{Age =} \FunctionTok{runif}\NormalTok{(}\AttributeTok{n=}\DecValTok{10}\NormalTok{, }\DecValTok{20}\NormalTok{, }\DecValTok{60}\NormalTok{))}
\end{Highlighting}
\end{Shaded}

Click for answer

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{example\_data}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
   ID Greeting  Male      Age
1   1    Hello  TRUE 56.41977
2   2    Hello FALSE 48.79070
3   3    Hello  TRUE 55.55897
4   4    Hello FALSE 25.95434
5   5    Hello  TRUE 26.33548
6   6  Goodbye FALSE 40.31555
7   7  Goodbye  TRUE 23.83351
8   8  Goodbye FALSE 43.08431
9   9  Goodbye  TRUE 50.55220
10 10  Goodbye FALSE 29.80661
\end{verbatim}

\emph{Answer:} We see a data frame with four columns, where the first column is an \texttt{identifier} for the cases. We have information on the greeting types, whether male or not, and age on these cases in the remaining columns.

\begin{enumerate}
\def\labelenumi{\alph{enumi}.}
\setcounter{enumi}{1}
\tightlist
\item
  What is the dimension of the dataset called `example\_data'?
\end{enumerate}

Click for answer

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{dim}\NormalTok{(example\_data)}
\NormalTok{[}\DecValTok{1}\NormalTok{] }\DecValTok{10}  \DecValTok{4}
\FunctionTok{nrow}\NormalTok{(example\_data)}
\NormalTok{[}\DecValTok{1}\NormalTok{] }\DecValTok{10}
\FunctionTok{ncol}\NormalTok{(example\_data)}
\NormalTok{[}\DecValTok{1}\NormalTok{] }\DecValTok{4}
\end{Highlighting}
\end{Shaded}

\emph{Answer:} There are 10 rows and 4 columns.

\begin{center}\rule{0.5\linewidth}{0.5pt}\end{center}

\hypertarget{your-turn-2}{%
\section{Your Turn 2}\label{your-turn-2}}

\begin{enumerate}
\def\labelenumi{\alph{enumi}.}
\tightlist
\item
  Read the dataset \texttt{EducationLiteracy} from the \href{https://www.lock5stat.com/datapage2e.html}{Lock5} second edition book.
\end{enumerate}

Click for answer

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{\# read in the data}
\NormalTok{education\_lock5 }\OtherTok{\textless{}{-}} \FunctionTok{read.csv}\NormalTok{(}\StringTok{"https://www.lock5stat.com/datasets2e/EducationLiteracy.csv"}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\begin{enumerate}
\def\labelenumi{\alph{enumi}.}
\setcounter{enumi}{1}
\tightlist
\item
  Print the header (i.e.~first 6 cases by default) of the dataset in part a.
\end{enumerate}

Click for answer

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{head}\NormalTok{(education\_lock5)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
              Country EducationExpenditure Literacy
1         Afghanistan                  3.1     31.7
2             Albania                  3.2     96.8
3             Algeria                  4.3       NA
4             Andorra                  3.2       NA
5              Angola                  3.5     70.6
6 Antigua and Barbuda                  2.6     99.0
\end{verbatim}

\begin{enumerate}
\def\labelenumi{\alph{enumi}.}
\setcounter{enumi}{2}
\tightlist
\item
  What is the dimension of the dataset in a?
\end{enumerate}

Click for answer

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{dim}\NormalTok{(education\_lock5)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
[1] 188   3
\end{verbatim}

\emph{Answer:} There are 188 rows and 3 columns.

\begin{enumerate}
\def\labelenumi{\alph{enumi}.}
\setcounter{enumi}{3}
\tightlist
\item
  What type of variables are \texttt{Country}, \texttt{EducationExpenditure}, and \texttt{Literacy}?
\end{enumerate}

Click for answer

\emph{Answer:} \texttt{Country} is a categorical variable. \texttt{EducationExpenditure} and \texttt{Literacy} are both quantitative variables.

\begin{enumerate}
\def\labelenumi{\alph{enumi}.}
\setcounter{enumi}{4}
\tightlist
\item
  If we would like to use education expenditure to predict the literacy rate of each countries, which variable is the explanatory variable and which one is the response?
\end{enumerate}

Click for answer

\emph{Answer:} The education expenditure is the explanatory variable, and the literacy rate is the response.

\begin{center}\rule{0.5\linewidth}{0.5pt}\end{center}

\hypertarget{quiz}{%
\section{Quiz}\label{quiz}}

\textbf{1. Cases are a set of individual units where the measurements are taken.}

  A. TRUE

  B. FALSE

Click for answer

TRUE

\textbf{2. The characteristic that is recorded for each case is called a}

 A. ledger

 B. caseholder

 C. placeholder

 D. variable

Click for answer

variable

\textbf{3. Variables can be either categorical or quantitative.}

 A. TRUE

 B. FALSE

Click for answer

TRUE

\hypertarget{class-activity-2}{%
\chapter{Class Activity 2}\label{class-activity-2}}

\hypertarget{your-turn-1-1}{%
\section{Your Turn 1}\label{your-turn-1-1}}

This exercise is about finding the average word length in Lincoln's Gettysburg's address.

\begin{center}\rule{0.5\linewidth}{0.5pt}\end{center}

\hypertarget{your-turn-2-1}{%
\section{Your Turn 2}\label{your-turn-2-1}}

\hypertarget{summary-of-article-on-it-depends-on-how-you-ask}{%
\subsection{\texorpdfstring{Summary of article on \href{https://jech.bmj.com/content/75/4/387.abstract}{It depends on how you ask!}}{Summary of article on It depends on how you ask!}}\label{summary-of-article-on-it-depends-on-how-you-ask}}

Click for answer

\emph{Answer:}

This study aimed to measure the effects of psychological biases on estimates of compliance with public health guidance regarding COVID-19. Results showed that compliance estimates were reduced when questions were framed negatively and anonymity was increased. Effect sizes were large, with compliance estimates diminishing by up to 17\% points and 10\% points, respectively. These findings suggest that standard tracking surveys pose questions in ways that lead to higher compliance estimates than alternative approaches.

\begin{center}\rule{0.5\linewidth}{0.5pt}\end{center}

\hypertarget{your-turn-3}{%
\section{Your Turn 3}\label{your-turn-3}}

\hypertarget{gettysburg-random-sample}{%
\subsection{Gettysburg random sample}\label{gettysburg-random-sample}}

Let's take a simple random sample (SRS) of Gettysburg words. The ``population'' is contained in the
spreadsheet \texttt{GettysburgPopulationCounts.csv}. Carefully load this data into R:

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{pop }\OtherTok{\textless{}{-}} \FunctionTok{read.csv}\NormalTok{(}\StringTok{"https://raw.githubusercontent.com/deepbas/statdatasets/main/GettysbergPopulationCounts.csv"}\NormalTok{)}
\FunctionTok{head}\NormalTok{(pop)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
  position size  word
1        1    4  Four
2        2    5 score
3        3    3   and
4        4    5 seven
5        5    5 years
6        6    3  ago,
\end{verbatim}

The \texttt{position} variable enumerates the list of words in the population (address).

(a). Sample

Run the following command to obtain a SRS of 10 words from the 268 that are in the population:

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{samp }\OtherTok{\textless{}{-}} \FunctionTok{sample}\NormalTok{(}\DecValTok{1}\SpecialCharTok{:}\DecValTok{268}\NormalTok{, }\AttributeTok{size=}\DecValTok{10}\NormalTok{)}
\NormalTok{samp}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
 [1] 186 217 162 190 256  58 171 264 116  14
\end{verbatim}

This tells you the position (row number) of your sampled words. What are your sampled positions? Why are your sampled positions different from other folks in class?

(b). Get words and lengths

We will \emph{subset} the data set \texttt{pop} to obtain only the sampled rows listed in \texttt{samp}. We do this using \textbf{square bracket notation} `dataset{[}row number, column number/name{]}. Run the following command to find your sampled words and sizes:

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{pop[samp,]}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
    position size      word
186      186    8 advanced.
217      217    4      they
162      162    2        is
190      190    3       for
256      256    6   people,
58        58    2        on
171      171    4      here
264      264    3       not
116      116    6    hallow
14        14    1         a
\end{verbatim}

\begin{enumerate}
\def\labelenumi{\alph{enumi}.}
\setcounter{enumi}{2}
\tightlist
\item
  Compute your sample mean
\end{enumerate}

The word lengths in part (b) are the data for your sample. You can compute your sample mean using a calculator, or using R. Let's try R (you will find it faster!). First save the quantitative variable \texttt{size} in a new variable called \texttt{mysize}:

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{mysize }\OtherTok{\textless{}{-}}\NormalTok{ pop[samp, }\StringTok{"size"}\NormalTok{]}
\NormalTok{mysize}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
 [1] 8 4 2 3 6 2 4 3 6 1
\end{verbatim}

Then find the mean of these values:

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{mean}\NormalTok{(mysize)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
[1] 3.9
\end{verbatim}

How does this sample mean (from a truly random sample) compare to your sample mean from the non-random sample?

Click for answer

\emph{Answer:} The true mean is 4.29. Your two means will likely vary. Since the many non-random samples generally overestimated the population mean length, it is possible (but not guaranteed) that \emph{your} one non-random sample gave a mean length that is greater than the random sample's mean length.

\hypertarget{driving-with-a-pet-on-your-lap}{%
\subsection{Driving with a Pet on your Lap}\label{driving-with-a-pet-on-your-lap}}

Over 30,000 people participated in an online poll on \texttt{cnn.com} conducted in April 2012 asking: ``Have you ever driven with a pet on your lap''? We see that 34\% of the participants answered yes and 66\% answered no.

\begin{enumerate}
\def\labelenumi{\alph{enumi}.}
\tightlist
\item
  Can you conclude that a random sample was used from the description given? Explain.
\end{enumerate}

Click for answer

\emph{Answer:} No you can't make this conclusion from the info given. In fact, an online poll at a website like \texttt{cnn.com} is almost always reporting results from a non-random sample. The people who respond are individuals who visit \texttt{cnn.com}, then see the online poll and decide to respond.

\begin{enumerate}
\def\labelenumi{\alph{enumi}.}
\setcounter{enumi}{1}
\tightlist
\item
  Explain why it is not appropriate to generalize these results to all drivers, or even to all drivers who visit cnn.com.
\end{enumerate}

Click for answer

\emph{Answer:} This is a volunteer sample, and volunteer samples are often biased and can't be generalized to \emph{all drivers} (the population). It is likely that people who have driven with a pet on their lap are more likely to respond to the poll.

\begin{enumerate}
\def\labelenumi{\alph{enumi}.}
\setcounter{enumi}{2}
\tightlist
\item
  How might we select a sample of people that would give us results that we can generalize to a broader population?
\end{enumerate}

Click for answer

\emph{Answer:} A random sample of individuals from all U.S. drivers would need to be selected and given the poll question. (There are many ways to do this, the most common being a variation of random digit dialing where phone numbers are randomly selected from known area codes.)

\begin{enumerate}
\def\labelenumi{\alph{enumi}.}
\setcounter{enumi}{3}
\tightlist
\item
  Is the variable measured in this study quantitative or categorical?
\end{enumerate}

Click for answer

\emph{Answer:} Categorical (yes or no answer to the question).

\begin{center}\rule{0.5\linewidth}{0.5pt}\end{center}

\hypertarget{quiz-1}{%
\section{Quiz}\label{quiz-1}}

\textbf{1. A group of researchers investigated the effect of media usage (whether or not subjects watch television or use the Internet) in the bedroom on ``Tiredness'' during the day (measured on a 50 point scale). The explanatory and response variables are}

  A. Explanatory is media usage in the bedroom and response is ``tiredness''

  B. Explanatory is ``tiredness'' and response is media usage in the bedroom

Click for answer

The correct answer is A.

\textbf{2. An October 2016 Gallup poll estimates that 60\% of US adults support legalizing the use of marijuana. Their results were based on a ``random sample of 1,017 adults, aged 18 and older, living in all 50 U.S. states and the District of Columbia''. The population for this study is}

 A. all adults (18 and older) living in the U.S. (including D.C)

 B. the 1,017 adults (18 and older) living in the U.S. (including D.C) who were sampled

 C. the 1,017 adults (18 and older) living in the U.S. (including D.C) who were sampled and support legalizing marijuana

 D. all adults (18 and older) living in the U.S. (including D.C) who support legalizing marijuana

Click for answer

The correct answer is A.

\textbf{3. An October 2016 Gallup poll estimates that 60\% of US adults support legalizing the use of marijuana. Their results were based on a ``random sample of 1,017 adults, aged 18 and older, living in all 50 U.S. states and the District of Columbia''. Which statement below regarding bias is true?}

 A. The results are biased because Gallup only contacted a small fraction of people in the population.

 B. The results may be biased because people may not have answered a survey question about marijuana truthfully

Click for answer

The correct answer is B.

\hypertarget{class-activity-3}{%
\chapter{Class Activity 3}\label{class-activity-3}}

\hypertarget{case-study-1}{%
\section{Case Study 1}\label{case-study-1}}

Consider the following case study:

``Swimming with dolphins can certainly be fun, but is it also therapeutic for patients suffering from clinical depression? To investigate this possibility, researchers recruited 30 subjects aged 18-65 with a clinical diagnosis of mild to moderate depression. Subjects were required to discontinue use of any antidepressant drugs or psychotherapy four weeks prior to the experiment, and throughout the experiment. These 30 subjects went to an island off the coast of Honduras, where they were randomly assigned to one of two treatment groups. Both groups engaged in the same amount of swimming and snorkeling each day, but one group (the animal care program) did so in the presence of bottlenose dolphins and the other group (outdoor nature program) did not. At the end of two weeks, each subjects' level of depression was evaluated, as it had been at the beginning of the study, and it was determined whether they showed substantial improvement (reducing their level of depression) by the end of the study (Antonioli and Reveley, 2005).''

Observed data:

The researchers found that 10 of 15 subjects in the dolphin therapy group showed substantial improvement, compared to 3 of 15 subjects in the control group.

(a). Identify the observational units in this study.

Click for answer

\emph{Answer:} The observational units in this study are the 30 subjects.

(b). Classify each variable as categorical or quantitative.

Click for answer

\emph{Answer:} The variables in this study can be classified as follows:
Categorical: Treatment Group (Dolphin and Control)
Quantitative: Age, Level of Depression (Beginning and End of Study)

(c). Which variable would you regard as explanatory and which as response?

Click for answer

\emph{Answer:} The explanatory variable would be the Treatment Group and the response variable would be the Level of Depression.

(d). Is this an observational study or an experiment? Justify your answer.

Click for answer

\emph{Answer:} This is an experiment because the researchers randomly assigned the subjects to the two treatment groups, and then observed the effect of the treatment (presence of dolphins) on the response variable (level of depression).

(e). Construct a two-way table based on the results of the experiment.

Click for answer

Two-way table:

\begin{longtable}[]{@{}llll@{}}
\toprule()
Treatment & Improved & Not Improved & Total \\
\midrule()
\endhead
Dolphin Group & 10 & 5 & 15 \\
Control Group & 3 & 12 & 15 \\
Total & 13 & 17 & 30 \\
\bottomrule()
\end{longtable}

\begin{center}\rule{0.5\linewidth}{0.5pt}\end{center}

\hypertarget{case-study-2}{%
\section{Case Study 2}\label{case-study-2}}

Consider the following case study:

``Researchers want to find out how a new diet affects weight gain among underweight subjects. This experiment only has two treatment conditions, the new diet and the standard diet. For this study, the researchers recruited 200 subjects which will be grouped into 100 pairs based on shared characteristics such as age, gender, weight, height, lifestyle, and so on. A 20-year-old female within the weight range of 90-110 pounds and the height range of 60-63 inches will be paired with another 20-year-old female that falls into the same weight and height categories. Once all 100 pairs are made, a subject from each pair will be randomly assigned into the treatment group (will be administered the new diet for 2 months) while the other subject from the pair will be assigned to the control group (will be assigned to follow the standard diet for two months). At the end of the time time period of 2 months, researchers will measure the total weight gain for each subject.''

Observed data:

The researchers found that 60 of 100 subjects in the new diet group showed substantial improvement, compared to 43 of 100 subjects in the standard diet group.

(a). Identify the observational units in this study.

Click for answer

\emph{Answer:} The observational units in this study are the 200 subjects.

(b). Classify each variable as categorical or quantitative.

Click for answer

\emph{Answer:} The variables are: age (quantitative), gender (categorical), weight (quantitative), height (quantitative), lifestyle (categorical), and total weight gain (quantitative).

(c). Which variable would you regard as explanatory and which as response?

Click for answer

\emph{Answer:} The explanatory variable is the type of diet (new or standard) and the response variable is the total weight gain.

(d). Is this an observational study or an experiment? Justify your answer.

Click for answer

\emph{Answer:} This is an experiment because the researchers are manipulating the explanatory variables (type of diet) to observe the effects on the response variables (total weight gain).

(e). If it is an experiment, is it randomized comparative experiment or a matched pairs experiment?

Click for answer

\emph{Answer:} This is a matched pairs experiment because each subject is paired with another subject who has similar characteristics and one subject from each pair is randomly assigned to the treatment group and the other to the control group.

(f). Construct a two-way table based on the results of the experiment.

Click for answer

Two-way table:

\begin{longtable}[]{@{}llll@{}}
\toprule()
Outcome & New Diet & Standard Diet & Total \\
\midrule()
\endhead
Improvement & 60 & 43 & 103 \\
No Improvement & 40 & 57 & 97 \\
Total & 100 & 100 & 200 \\
\bottomrule()
\end{longtable}

\begin{center}\rule{0.5\linewidth}{0.5pt}\end{center}

\hypertarget{quiz-2}{%
\section{Quiz}\label{quiz-2}}

\textbf{1. A third variable that is associated with both the explanatory variable and the response variable is called a confounding variable.}

  A. TRUE

  B. FALSE

Click for answer

TRUE

\textbf{2. The different levels of an explanatory variable are known as }

 A. treatments

 B. local groups

 C. response

 D. cases

Click for answer

treatments

\textbf{3. Causality can always be inferred from observational studies.}

 A. TRUE

 B. FALSE

Click for answer

FALSE

\hypertarget{class-activity-4}{%
\chapter{Class Activity 4}\label{class-activity-4}}

\hypertarget{your-turn-1-2}{%
\section{Your Turn 1}\label{your-turn-1-2}}

\hypertarget{flowers-v.-mississippi}{%
\subsection{Flowers v. Mississippi}\label{flowers-v.-mississippi}}

The data set \texttt{APM\_DougEvensCases.csv} contains data from 1517 potential black and white jurors for 66 cases that Doug Evans was primary prosecutor for between 1992 and 2017. These jurors were available for Doug Evans to strike using his ``peremptory strikes'' during the jury selection phase.

(a). Inspect data

Read in the data

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{jurors }\OtherTok{\textless{}{-}} \FunctionTok{read.csv}\NormalTok{(}\StringTok{"https://raw.githubusercontent.com/deepbas/statdatasets/main/APM\_DougEvansCases.csv"}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{\# dimension of dataset}
\FunctionTok{dim}\NormalTok{(jurors)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
[1] 1517    6
\end{verbatim}

Look at the first \textbf{three rows} of the data set

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{jurors[}\FunctionTok{c}\NormalTok{(}\DecValTok{1}\NormalTok{,}\DecValTok{2}\NormalTok{,}\DecValTok{3}\NormalTok{), ]}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
  trial__id  race        struck_state defendant_race
1         4 Black Not struck by State          White
2         4 Black     Struck by State          White
3         4 White Not struck by State          White
       same_race                     struck_by
1 different race Juror chosen to serve on jury
2 different race           Struck by the state
3      same race Juror chosen to serve on jury
\end{verbatim}

To get the data from one variable, we use the command \texttt{dataset\$variable}. For example, \texttt{jurors\$struck\_state} gives us the data values from the \texttt{struck\_state} variable, which tells us if a juror was struck by the state from the jury pool. Here we can see the first 10 entries in this variable:

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{jurors}\SpecialCharTok{$}\NormalTok{struck\_state[}\DecValTok{1}\SpecialCharTok{:}\DecValTok{10}\NormalTok{]}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
 [1] "Not struck by State" "Struck by State"    
 [3] "Not struck by State" "Not struck by State"
 [5] "Struck by State"     "Not struck by State"
 [7] "Struck by State"     "Not struck by State"
 [9] "Not struck by State" "Not struck by State"
\end{verbatim}

(b). Table of counts and proportions

The \texttt{summary} command used with a data frame gives summaries of each variable

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{summary}\NormalTok{(jurors)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
   trial__id         race           struck_state      
 Min.   :  4.0   Length:1517        Length:1517       
 1st Qu.: 52.0   Class :character   Class :character  
 Median : 82.0   Mode  :character   Mode  :character  
 Mean   :112.6                                        
 3rd Qu.:170.0                                        
 Max.   :301.0                                        
 defendant_race      same_race          struck_by        
 Length:1517        Length:1517        Length:1517       
 Class :character   Class :character   Class :character  
 Mode  :character   Mode  :character   Mode  :character  
                                                         
                                                         
                                                         
\end{verbatim}

The \texttt{table} command gives the distribution of counts for a single categorical variable. To obtain the count table for \texttt{struck\_state} you need to

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{counts }\OtherTok{\textless{}{-}} \FunctionTok{table}\NormalTok{(jurors}\SpecialCharTok{$}\NormalTok{struck\_state)}
\NormalTok{counts}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}

Not struck by State     Struck by State 
               1084                 433 
\end{verbatim}

We can add the \texttt{prop.table} command to turn these counts into proportions:

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{prop.table}\NormalTok{(counts)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}

Not struck by State     Struck by State 
          0.7145682           0.2854318 
\end{verbatim}

\begin{itemize}
\tightlist
\item
  What proportion of eligible jurors were struck by the state from the jury pool?
\end{itemize}

Click for answer

\emph{Answer:} about 28.5\% of eligible jurors were struck by the state.

(c). Bar graph for one variable

You can create a simple bar graph for one categorical variable with the \texttt{barplot} command. Here we visualize the distribution of struck status for all eligible jurors:

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{barplot}\NormalTok{(counts, }\AttributeTok{ylab =} \StringTok{"count"}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\includegraphics[width=1\linewidth]{Class_Activity_4_files/figure-latex/unnamed-chunk-8-1}

(d). Two-way tables

First 10 entries of \texttt{race} and \texttt{struck\_state} variable is

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{jurors[(}\DecValTok{1}\SpecialCharTok{:}\DecValTok{10}\NormalTok{),(}\DecValTok{2}\SpecialCharTok{:}\DecValTok{3}\NormalTok{)]}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
    race        struck_state
1  Black Not struck by State
2  Black     Struck by State
3  White Not struck by State
4  White Not struck by State
5  Black     Struck by State
6  White Not struck by State
7  Black     Struck by State
8  White Not struck by State
9  White Not struck by State
10 White Not struck by State
\end{verbatim}

The \texttt{table} command also gives two-way tables when two variables are included. Here is the two-way table for juror race and state struck status:

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{mytable }\OtherTok{\textless{}{-}} \FunctionTok{table}\NormalTok{(jurors}\SpecialCharTok{$}\NormalTok{race, jurors}\SpecialCharTok{$}\NormalTok{struck\_state)}
\NormalTok{mytable}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
       
        Not struck by State Struck by State
  Black                 225             310
  White                 859             123
\end{verbatim}

\begin{itemize}
\tightlist
\item
  How many jurors were white and were not struck by the state?
\end{itemize}

Click for answer

\emph{answer:} 859

(e). Conditional proportions: state strike status by juror race

The \texttt{prop.table} command gives conditional proportions for a two-way table. We plug our two-way table into \texttt{prop.table} with a \texttt{margin=1} to get proportions grouped by the \textbf{row} variable:

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{prop.table}\NormalTok{(mytable, }\AttributeTok{margin =} \DecValTok{1}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
       
        Not struck by State Struck by State
  Black           0.4205607       0.5794393
  White           0.8747454       0.1252546
\end{verbatim}

Of all eligible black jurors, about 57.9\% were struck by the state.

\begin{itemize}
\tightlist
\item
  What proportion of eligible white jurors were struck by the state?

  Click for answer

  \emph{answer:} about 12.5\%
\item
  Is there evidence of an association between juror race and state strikes?

  Click for answer

  \emph{answer:} Yes, there is an association because the rate of state strikes varies greatly by juror race with
  about 60\% of black jurors were struck compared to only 13\% of white jurors
\end{itemize}

(f). Stacked bar graph for two variables

We can visualize the conditional distribution from part (e) with a stacked bar graph created using the \texttt{ggplot2} graphing package. First, load this package's functions with the \texttt{library} command:

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{library}\NormalTok{(ggplot2)}
\end{Highlighting}
\end{Shaded}

Now we can use the \texttt{geom\_bar} command in this package. Here we get the conditional distribution of \texttt{struck\_state} given \texttt{race}:

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{ggplot}\NormalTok{(jurors, }\FunctionTok{aes}\NormalTok{(}\AttributeTok{x =}\NormalTok{ race, }\AttributeTok{fill =}\NormalTok{ struck\_state)) }\SpecialCharTok{+} 
  \FunctionTok{geom\_bar}\NormalTok{(}\AttributeTok{position =} \StringTok{"fill"}\NormalTok{) }\SpecialCharTok{+} 
  \FunctionTok{labs}\NormalTok{(}\AttributeTok{title =} \StringTok{"State strikes by juror race"}\NormalTok{, }\AttributeTok{y =} \StringTok{"proportion"}\NormalTok{, }
       \AttributeTok{x =} \StringTok{"eligible juror race"}\NormalTok{, }\AttributeTok{fill =} \StringTok{"struck by state?"}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\includegraphics[width=1\linewidth]{Class_Activity_4_files/figure-latex/unnamed-chunk-13-1}

The basic syntax for this function is to let \texttt{ggplot} know your data set name (\texttt{jurors}), then specify the grouping or conditional variable on the x-axis (\texttt{race}) in the \texttt{aes} (aesthetic) argument. The \texttt{fill} variable is the response variable (\texttt{struck\_state}). We add (\texttt{+}) the \texttt{geom\_bar} geometry to get a bar graph with the \texttt{fill} position specified. Adding an informative label and title complete the graph.

(g). Conditional distribution of race grouped by strike status

We can ``flip'' our response and grouping variables easily (if we think it makes sense to do so). Here we specify the \texttt{margin=2} to get proportions grouped by the \textbf{column} variable:

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{prop.table}\NormalTok{(mytable, }\AttributeTok{margin =} \DecValTok{2}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
       
        Not struck by State Struck by State
  Black           0.2075646       0.7159353
  White           0.7924354       0.2840647
\end{verbatim}

Notice that the proportions add to one \textbf{down} each column. Of all eligible jurors struck by the state, about 71.6\% were black.

The stacked bar graph for this distribution is

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{ggplot}\NormalTok{(jurors, }\FunctionTok{aes}\NormalTok{(}\AttributeTok{x =}\NormalTok{ struck\_state, }\AttributeTok{fill =}\NormalTok{ race)) }\SpecialCharTok{+} 
  \FunctionTok{geom\_bar}\NormalTok{(}\AttributeTok{position =} \StringTok{"fill"}\NormalTok{) }\SpecialCharTok{+} 
  \FunctionTok{labs}\NormalTok{(}\AttributeTok{title =} \StringTok{"Juror race by state strikes"}\NormalTok{, }\AttributeTok{y =} \StringTok{"proportion"}\NormalTok{, }
       \AttributeTok{fill =} \StringTok{"eligible juror race"}\NormalTok{, }\AttributeTok{x =} \StringTok{"struck by state?"}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\includegraphics[width=1\linewidth]{Class_Activity_4_files/figure-latex/unnamed-chunk-15-1}

\begin{itemize}
\tightlist
\item
  What proportion of eligible jurors who were not struck by the state were black? were white?
\end{itemize}

Click for answer

\emph{Answer:} Of all jurors not struck by the state, about 20.8\% were black

\begin{center}\rule{0.5\linewidth}{0.5pt}\end{center}

\hypertarget{your-turn-2-2}{%
\section{Your Turn 2}\label{your-turn-2-2}}

\hypertarget{graduate-programs-acceptance-and-sex}{%
\subsection{Graduate programs acceptance and sex}\label{graduate-programs-acceptance-and-sex}}

How are grad school program acceptance rates associated with sex? We will look at a classic data set from Berkeley grad school applications from 1973 (\emph{Science}, 1975). The data cases are applicants to four graduate programs at Berkeley during 1973. The variable \texttt{result} tells us if the applicant was accepted to the graduate program, \texttt{sex} tells us the sex of the applicant (male or female), and \texttt{program} tells us program type (programs 1,2,3 or 4).

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{grad }\OtherTok{\textless{}{-}} \FunctionTok{read.csv}\NormalTok{(}\StringTok{"https://raw.githubusercontent.com/deepbas/statdatasets/main/BerkeleyGrad.csv"}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{\# dimension of the dataset}
\FunctionTok{dim}\NormalTok{(grad)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
[1] 3014    3
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{\# first 6 rows}
\FunctionTok{head}\NormalTok{(grad)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
   program  sex result
1 program1 male accept
2 program1 male accept
3 program1 male accept
4 program1 male accept
5 program1 male accept
6 program1 male accept
\end{verbatim}

(a). Table of counts and proportions

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{prop.table}\NormalTok{(}\FunctionTok{table}\NormalTok{(grad}\SpecialCharTok{$}\NormalTok{result))}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}

   accept    reject 
0.4260119 0.5739881 
\end{verbatim}

\begin{itemize}
\tightlist
\item
  What proportion of applicants were accepted?
\end{itemize}

Click for answer

\emph{Answer:} About 43\% (1284/3014) of applicants were accepted.

(b). Two-way tables

The \texttt{table} command also gives two-way tables when two variables are included. Here is the two-way table for result and sex:

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{table}\NormalTok{(grad}\SpecialCharTok{$}\NormalTok{sex, grad}\SpecialCharTok{$}\NormalTok{result)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
        
         accept reject
  female    262    587
  male     1022   1143
\end{verbatim}

\begin{itemize}
\tightlist
\item
  How many applicants involved females who were accepted?
\end{itemize}

Click for answer

\emph{Answer:} : 262 applicants involved females who were accepted.

(c). Conditional proportions: acceptance given sex

The \texttt{prop.table} command gives conditional proportions for a two-way table. First let's save the two-way table in an object named \texttt{mytable}:

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{mytable }\OtherTok{\textless{}{-}} \FunctionTok{table}\NormalTok{(grad}\SpecialCharTok{$}\NormalTok{sex, grad}\SpecialCharTok{$}\NormalTok{result)}
\end{Highlighting}
\end{Shaded}

Then use \texttt{prop.table} to get the distribution of result conditioned (grouped) on applicant's sex:

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{prop.table}\NormalTok{(mytable, }\DecValTok{1}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
        
            accept    reject
  female 0.3085984 0.6914016
  male   0.4720554 0.5279446
\end{verbatim}

The value of \texttt{1} in this command tell's R that you want \emph{row} proportions (the denominator of the proportion is each row total).

\begin{itemize}
\tightlist
\item
  What proportion of female were accepted?
\end{itemize}

Click for answer

\emph{Answer:} about 31\% (262/(262+587))

\begin{itemize}
\tightlist
\item
  What proportion of males were accepted?
\end{itemize}

Click for answer

\emph{Answer:} about 47\% (1022/(1022+1143))

(d). Bar graph for one variable

You can create a simple bar graph for one categorical variable with the \texttt{barplot} command. Here we visualize the distribution of result:

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{barplot}\NormalTok{(}\FunctionTok{table}\NormalTok{(grad}\SpecialCharTok{$}\NormalTok{result))}
\end{Highlighting}
\end{Shaded}

\includegraphics[width=1\linewidth]{Class_Activity_4_files/figure-latex/unnamed-chunk-23-1}

We can add in a title and x and y axis labels too:

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{barplot}\NormalTok{(}\FunctionTok{table}\NormalTok{(grad}\SpecialCharTok{$}\NormalTok{result), }\AttributeTok{xlab=}\StringTok{"application result"}\NormalTok{, }
        \AttributeTok{ylab=}\StringTok{"Count"}\NormalTok{, }\AttributeTok{main =} \StringTok{"Distribution of Results"}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\includegraphics[width=1\linewidth]{Class_Activity_4_files/figure-latex/unnamed-chunk-24-1}

(e). Stacked bar graph for two variables

Now we can use the \texttt{geom\_bar} command in this package. Here we get the conditional distribution of \texttt{result} given \texttt{sex}:

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{library}\NormalTok{(ggplot2) }\CommentTok{\# don\textquotesingle{}t need if you already entered it for example 1}
\FunctionTok{ggplot}\NormalTok{(grad, }\FunctionTok{aes}\NormalTok{(}\AttributeTok{x =}\NormalTok{ sex, }\AttributeTok{fill =}\NormalTok{ result)) }\SpecialCharTok{+} 
  \FunctionTok{geom\_bar}\NormalTok{(}\AttributeTok{position =} \StringTok{"fill"}\NormalTok{) }\SpecialCharTok{+} 
  \FunctionTok{labs}\NormalTok{(}\AttributeTok{y=}\StringTok{"Proportion"}\NormalTok{, }\AttributeTok{title =} \StringTok{"result by sex"}\NormalTok{, }\AttributeTok{fill =} \StringTok{"result?"}\NormalTok{, }\AttributeTok{x =} \StringTok{"sex"}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\includegraphics[width=1\linewidth]{Class_Activity_4_files/figure-latex/unnamed-chunk-25-1}

The basic syntax for this function is to let \texttt{ggplot} know your data set name (\texttt{grad}), then specify the grouping or conditional variable on the x-axis (\texttt{sex}) in the \texttt{aes} (aesthetic) argument. The \texttt{fill} variable is the response variable (\texttt{result}). We add (\texttt{+}) the \texttt{geom\_bar} geometry to get a bar graph with the \texttt{fill} position specified. Adding an informative label and title complete the graph.

\begin{itemize}
\tightlist
\item
  Verify that this graph is plotting the conditional proportions from part (c)
\end{itemize}

(f). Subsetting by program type

Finally, we will repeat the previous analysis of result and sex, but this time we will divide (or subset) the data set by program type. To do this we need to know how the values of \texttt{program} are coded:

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{table}\NormalTok{(grad}\SpecialCharTok{$}\NormalTok{program)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}

program1 program2 program3 program4 
     933      585      782      714 
\end{verbatim}

Here we use the \texttt{filter} command available from the \texttt{dplyr} package to get only the applicants to program 1:

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{library}\NormalTok{(dplyr)}
\NormalTok{grad.p1 }\OtherTok{\textless{}{-}} \FunctionTok{filter}\NormalTok{(grad, program }\SpecialCharTok{==} \StringTok{"program1"}\NormalTok{)  }\CommentTok{\# gets rows where program equal program1}
\FunctionTok{head}\NormalTok{(grad.p1)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
   program  sex result
1 program1 male accept
2 program1 male accept
3 program1 male accept
4 program1 male accept
5 program1 male accept
6 program1 male accept
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{dim}\NormalTok{(grad.p1)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
[1] 933   3
\end{verbatim}

Verify that the number of rows in the subsetted program 1 data set matches the number of program 1 applicants shown in the \texttt{table} of counts above.

\begin{itemize}
\tightlist
\item
  Repeat the \texttt{filter} command to get a data set for program 2 and call the new data set \texttt{grad.p2}. Verify that the number of rows in this dataset matches the number of program 2 applicants in the original data set.
\end{itemize}

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{\# enter R code for (f) here}
\NormalTok{grad.p2 }\OtherTok{\textless{}{-}} \FunctionTok{filter}\NormalTok{(grad, program }\SpecialCharTok{==} \StringTok{"program2"}\NormalTok{) }\CommentTok{\# gets rows where program equal program1}
\FunctionTok{head}\NormalTok{(grad.p2)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
   program  sex result
1 program2 male accept
2 program2 male accept
3 program2 male accept
4 program2 male accept
5 program2 male accept
6 program2 male accept
\end{verbatim}

(g). Result by sex for program 1.

\begin{itemize}
\tightlist
\item
  Show the distribution of result conditioned on applicant's sex for the program 1 data set. Get both a table of conditional proportions (or percentages) and a stacked bar graph.
\end{itemize}

Click for answer

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{\# enter R code for (g) here}
\FunctionTok{ggplot}\NormalTok{(grad.p1, }\FunctionTok{aes}\NormalTok{(}\AttributeTok{x =}\NormalTok{ sex, }\AttributeTok{fill =}\NormalTok{ result)) }\SpecialCharTok{+}
 \FunctionTok{geom\_bar}\NormalTok{(}\AttributeTok{position =} \StringTok{"fill"}\NormalTok{) }\SpecialCharTok{+}
 \FunctionTok{labs}\NormalTok{(}\AttributeTok{y=}\StringTok{"Proportion"}\NormalTok{, }\AttributeTok{title =} \StringTok{"result by sex for program 1"}\NormalTok{,}
 \AttributeTok{fill =} \StringTok{"result?"}\NormalTok{, }\AttributeTok{x =} \StringTok{"sex"}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\includegraphics[width=1\linewidth]{Class_Activity_4_files/figure-latex/unnamed-chunk-29-1}

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{prop.table}\NormalTok{(}\FunctionTok{table}\NormalTok{(grad.p1}\SpecialCharTok{$}\NormalTok{sex, grad.p1}\SpecialCharTok{$}\NormalTok{result),}\DecValTok{1}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
        
            accept    reject
  female 0.8240741 0.1759259
  male   0.6193939 0.3806061
\end{verbatim}

(h). Result by sex for program 2.

\begin{itemize}
\tightlist
\item
  Repeat part (g) but this time use the program 2 data set. Compare the two bar graphs for (g) and (h) and explain how they show that females have a higher acceptance rate after accounting for program type (1 or 2).
\end{itemize}

Click for answer

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{\# enter R code for (h) here}
\FunctionTok{ggplot}\NormalTok{(grad.p2, }\FunctionTok{aes}\NormalTok{(}\AttributeTok{x =}\NormalTok{ sex, }\AttributeTok{fill =}\NormalTok{ result)) }\SpecialCharTok{+}
 \FunctionTok{geom\_bar}\NormalTok{(}\AttributeTok{position =} \StringTok{"fill"}\NormalTok{) }\SpecialCharTok{+}
 \FunctionTok{labs}\NormalTok{(}\AttributeTok{y=}\StringTok{"Proportion"}\NormalTok{, }\AttributeTok{title =} \StringTok{"result by sex for program 2"}\NormalTok{,}
 \AttributeTok{fill =} \StringTok{"result?"}\NormalTok{, }\AttributeTok{x =} \StringTok{"sex"}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\includegraphics[width=1\linewidth]{Class_Activity_4_files/figure-latex/unnamed-chunk-31-1}

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{prop.table}\NormalTok{(}\FunctionTok{table}\NormalTok{(grad.p2}\SpecialCharTok{$}\NormalTok{sex, grad.p2}\SpecialCharTok{$}\NormalTok{result),}\DecValTok{1}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
        
            accept    reject
  female 0.6800000 0.3200000
  male   0.6285714 0.3714286
\end{verbatim}

\emph{Answer:} For both programs 1 and 2, we see that female applicants have a slightly higher rate of acceptance
than male applicants. After accounting for program type, we now see that black defendants have a higher
rate of death penalty than white defendants. Without accounting for program type, the opposite was true
(see parts (c) and (e)).

Why? the confounding affect of program type which is associated with both result and sex:

Click for answer

\begin{itemize}
\tightlist
\item
  females prefer to apply to programs 3 and 4 while males prefer programs 1 and 2 (more than 3 and
  4).

  \begin{itemize}
  \tightlist
  \item
    44\% of females applied to program 3 and 40\% to program 4
  \item
    38\% of males applied to program 1 and 26\% to program 2
  \end{itemize}
\end{itemize}

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{prop.table}\NormalTok{(}\FunctionTok{table}\NormalTok{(grad}\SpecialCharTok{$}\NormalTok{sex, grad}\SpecialCharTok{$}\NormalTok{program), }\DecValTok{1}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
        
           program1   program2   program3   program4
  female 0.12720848 0.02944641 0.44169611 0.40164900
  male   0.38106236 0.25866051 0.18799076 0.17228637
\end{verbatim}

-Programs 3 and 4 were much harder to get into than programs 1 and 2
- 64\% of applicants to program 1 were accepted and 63\% of applicants to program 2 were accepted
- 6\% of applicants to program 4 were accepted and 34\% of applicants to program 3 were accepted

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{prop.table}\NormalTok{(}\FunctionTok{table}\NormalTok{(grad}\SpecialCharTok{$}\NormalTok{program, grad}\SpecialCharTok{$}\NormalTok{result), }\DecValTok{1}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
          
               accept     reject
  program1 0.64308682 0.35691318
  program2 0.63076923 0.36923077
  program3 0.34398977 0.65601023
  program4 0.06442577 0.93557423
\end{verbatim}

So since the majority of females applied to the toughest programs (as measured by acceptance rates),
there overall rate of acceptance was lower for females compared to males. But when we break down
these rates by program type, we see that females have higher acceptance rates than males (see the
visual in part (i)).

(i). A bar graph with three variables

If we simply want to graph the relationship between result and sex for each type of program, we can avoid subsetting the data by using the \texttt{facet\_wrap} command in \texttt{ggplot2}. It is one simple addition to the stacked bar graph in part (e):

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{ggplot}\NormalTok{(grad, }\FunctionTok{aes}\NormalTok{(}\AttributeTok{x =}\NormalTok{ sex, }\AttributeTok{fill =}\NormalTok{ result)) }\SpecialCharTok{+} 
  \FunctionTok{geom\_bar}\NormalTok{(}\AttributeTok{position =} \StringTok{"fill"}\NormalTok{) }\SpecialCharTok{+} 
  \FunctionTok{labs}\NormalTok{(}\AttributeTok{y=}\StringTok{"Proportion"}\NormalTok{, }
       \AttributeTok{title =} \StringTok{"result by sex for each program"}\NormalTok{, }
       \AttributeTok{fill =} \StringTok{"result?"}\NormalTok{, }
       \AttributeTok{x =} \StringTok{"sex"}\NormalTok{) }\SpecialCharTok{+} 
  \FunctionTok{facet\_wrap}\NormalTok{(}\SpecialCharTok{\textasciitilde{}}\NormalTok{program)}
\end{Highlighting}
\end{Shaded}

\includegraphics[width=1\linewidth]{Class_Activity_4_files/figure-latex/unnamed-chunk-35-1}

\begin{itemize}
\tightlist
\item
  Verify that this command creates side-by-side stacked bar graphs that match your graphs in parts (g) and (h) for programs 1 and 2.
\end{itemize}

Click for answer

\emph{Answer:} The graphs match.

\begin{center}\rule{0.5\linewidth}{0.5pt}\end{center}

\hypertarget{quiz-3}{%
\section{Quiz}\label{quiz-3}}

\textbf{1. A two-way table is shown for two groups, 1 and 2, and two possible outcomes, A and B.}

\begin{longtable}[]{@{}llll@{}}
\toprule()
~ & Outcome A & Outcome B & Total \\
\midrule()
\endhead
Group 1 & 40 & 10 & 50 \\
Group 2 & 30 & 120 & 150 \\
Total & 70 & 130 & 200 \\
\bottomrule()
\end{longtable}

\textbf{What proportion of all cases are in Group 1?}

  A. 0.33

  B. 0.20

  C. 0.25

  D. 0.75

Click for answer

C. 0.25

\textbf{2. A disruption of a gene called DYXC1 on chromosome 15 for humans may be related to an increased risk of developing dyslexia. Researchers studied the gene in 109 people diagnosed with dyslexia and in a control group of 195 others who had no learning disorder. The DYXC1 break occurred in 10 of those with dyslexia and in 5 of those in the control group. Is this an experiment or an observational study?}

 A. Experiment

 B. Observational Study

Click for answer

Observational Study

\textbf{3. The data from question 3 can be summarized in a two way table as:}

\begin{longtable}[]{@{}llll@{}}
\toprule()
~ & Gene Break & No Break & Total \\
\midrule()
\endhead
Dyslexia Group & 10 & 99 & 109 \\
Control Group & 5 & 190 & 195 \\
Total & 15 & 289 & 304 \\
\bottomrule()
\end{longtable}

\textbf{What is the proportion of Dyslexia group who have the break on the DYXC1 gene? Round your answer to 3 significant digits after the decimal.}

 A. 0.026

 B. 0.667

 C. 0.127

 D. 0.092

Click for answer

D. 0.092

\hypertarget{part-basics-r}{%
\chapter{(PART*) Basics R}\label{part-basics-r}}

\hypertarget{what-is-r}{%
\chapter{What is R?}\label{what-is-r}}

R is a free and open source statistical programming language that facilitates statistical computation. There are a myriad of application that can be done in R, thanks to a huge online support community and dedicated packages. However, R has no graphical user interface and it has to be run by typing commands into a text interface.

\hypertarget{what-is-rstudio}{%
\section{What is RStudio?}\label{what-is-rstudio}}

RStudio provides graphical interface to R! You can think of RStudio as a graphical front-end to R that that provides extra functionality. The use of the R programming language with the RStudio interface is an essential component of this course.

\hypertarget{r-studio-server}{%
\section{R Studio Server}\label{r-studio-server}}

The quickest way to get started is to go to \url{https://maize.mathcs.carleton.edu}, which opens an R Studio window in your web browser. Once logged in, I recommend that you do the following:

\begin{itemize}
\tightlist
\item
  Step 1: Create a folder for this course where you can save all of your work. In the Files window, click on New Folder.
\item
  Step 2: Click on Tools -\textgreater{} Global Options -\textgreater{} R Markdown. Then uncheck the box that says ``Show output inline\ldots{}''
\end{itemize}

(It is also possible to download RStudio on your own laptop. Instructions may be found at the end of this document.)

\hypertarget{r-markdown-basics}{%
\section{R Markdown Basics}\label{r-markdown-basics}}

An R Markdown file (.Rmd file) combines R commands and written analyses, which are `knit' together into an HTML, PDF, or Microsoft Word document.

An R Markdown file contains three essential elements:

\begin{itemize}
\item
  Header: The header (top) of the file contains information like the document title, author, date and your preferred output format (pdf\_document, word\_document, or html\_document).
\item
  Written analysis: You write up your analysis after the header and embed R code where needed. The online help below shows ways to add formatting details like bold words, lists, section labels, etc to your final pdf/word/html document. For example, adding ** before and after a word will bold that word in your compiled document.
\item
  R chunks: R chunks contain the R commands that you want evaluated. You embed these chunks within your written analysis and they are evaluated when you compile the document.
\end{itemize}

\hypertarget{installing-rrstudio-not-needed-if-you-are-using-the-maize-server}{%
\section{Installing R/RStudio (not needed if you are using the maize server)}\label{installing-rrstudio-not-needed-if-you-are-using-the-maize-server}}

\begin{itemize}
\tightlist
\item
  Download the latest version of R:

  \begin{itemize}
  \tightlist
  \item
    Windows: \url{http://cran.r-project.org/bin/windows/base/}
  \item
    Mac: \url{http://cran.r-project.org/bin/macosx/}
  \end{itemize}
\item
  Download the free Rstudio desktop version (Windows or Mac): \url{https://www.rstudio.com/products/rstudio/download/}
\end{itemize}

Use the default download and install options for each.

\hypertarget{install-latex-for-knitting-r-markdown-documents-to-pdf}{%
\section{Install LaTeX (for knitting R Markdown documents to PDF):}\label{install-latex-for-knitting-r-markdown-documents-to-pdf}}

If you want to compile R Markdown to .pdf files, you also need a LaTeX distribution (Note: this is not necessary if you choose to compile as a Word document.) Click \href{http://www.miktex.org/}{instructions for Windows} or \href{https://tug.org/mactex/}{instructions for Mac}, depending on your operating system to complete the installation.

\hypertarget{updating-rrstudio-not-needed-if-you-are-using-the-maize-server}{%
\section{Updating R/RStudio (not needed if you are using the maize server)}\label{updating-rrstudio-not-needed-if-you-are-using-the-maize-server}}

If you have used a local version of R/RStudio before and it is still installed on your machine, then you should make sure that you have the most recent versions of each program.

\begin{itemize}
\item
  To check your version of R, run the command \texttt{getRversion()} and compare your version to the newest version posted on \url{https://cran.r-project.org/}. If you need an update, then install the newer version using the installation directions above.
\item
  In RStudio, check for updates with the menu option \texttt{Help\ \textgreater{}\ Check\ for\ updates}. Follow directions if an update is needed.
\end{itemize}

\hypertarget{instructions}{%
\section{Instructions}\label{instructions}}

If using Rstudio on your computer, using the \textbf{File\textgreater Open File} menu to find and open this .Rmd file.

If using Maize Rstudio from your browser:

\begin{itemize}
\item
  In the Files tab, select \textbf{Upload} and \textbf{Choose File} to find the .Rmd that you downloaded. Click \emph{OK} to upload to your course folder/location in the maize server account.
\item
  Click on the .Rmd file in the appropriate folder to open the file.
\end{itemize}

Extra notes:

\begin{itemize}
\item
  You can run a line of code by placing your cursor in the line of code and clicking \textbf{Run Selected Line(s)}
\item
  You can run an entire chunk by clicking the green triangle on the right side of the code chunk.
\item
  After each small edit or code addition, \textbf{Knit} your Markdown. If you wait until the end to Knit, it will be harder to find errors in your work.
\item
  Format output type: You can use any of pdf\_document, html\_document type, or word\_document type.
\item
  \textbf{Maize users}: You may also need to allow for ``pop-up'' in your web browser when knitting documents.
\end{itemize}

\hypertarget{few-more-instructions}{%
\section{Few More Instructions}\label{few-more-instructions}}

The default setting in Rstudio when you are running chunks is that the ``output'' (numbers, graphs) are
shown \textbf{inline} within the Markdown Rmd. If you prefer to have your plots appear on the right of the console and not below the chunk, then change the settings as follows:

\begin{enumerate}
\def\labelenumi{\arabic{enumi}.}
\tightlist
\item
  Select Tools \textgreater{} Global Options.
\item
  Click the R Markdown section and uncheck (if needed) the option Show output inline for all
  R Markdown documents.
\item
  Click OK.
\end{enumerate}

Now try running R chunks in the .Rmd file to see the difference. You can recheck this box if you prefer
the default setting.

\hypertarget{r-markdown}{%
\chapter{R Markdown}\label{r-markdown}}

This is a R Markdown document. Markdown is a simple formatting syntax for authoring HTML, PDF, and MS Word documents. For more details on using R Markdown see \url{http://rmarkdown.rstudio.com}.

You can use asterisk mark to provide emphasis, such as \texttt{*italics*\ or\ **bold**}.

You can create lists with a dash:

\begin{Shaded}
\begin{Highlighting}[]
\SpecialCharTok{{-}}\NormalTok{ Item }\DecValTok{1}
\SpecialCharTok{{-}}\NormalTok{ Item }\DecValTok{2}
\SpecialCharTok{{-}}\NormalTok{ Item }\DecValTok{3}
  \SpecialCharTok{+}\NormalTok{ Subitem }\DecValTok{1}
\SpecialCharTok{*}\NormalTok{ Item }\DecValTok{4}
\end{Highlighting}
\end{Shaded}

\begin{itemize}
\tightlist
\item
  Item 1
\item
  Item 2
\item
  Item 3

  \begin{itemize}
  \tightlist
  \item
    Subitem 1
  \end{itemize}
\item
  Item 4
\end{itemize}

You can embed Latex equations in-line, \(\frac{1}{n} \sum_{i=1}^{n} x_{i}\) or in a new line as

\[\text{Var}(X) = \frac{1}{n-1}\sum_{i-1}^{n} (x_{i} - \bar{x})^2 \]
\#\# Embed an R code chunk:

Use

\begin{verbatim}
```r
Use back ticks to 
create a block of code
```
\end{verbatim}

to produce:

\begin{verbatim}
Use back ticks to 
create a block of code
\end{verbatim}

You can also evaluate and display the results of R code. Each tasks can be accomplished in a suitably labeled chunk like the following:

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{summary}\NormalTok{(cars)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
     speed           dist       
 Min.   : 4.0   Min.   :  2.00  
 1st Qu.:12.0   1st Qu.: 26.00  
 Median :15.0   Median : 36.00  
 Mean   :15.4   Mean   : 42.98  
 3rd Qu.:19.0   3rd Qu.: 56.00  
 Max.   :25.0   Max.   :120.00  
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{fit }\OtherTok{\textless{}{-}} \FunctionTok{lm}\NormalTok{(dist }\SpecialCharTok{\textasciitilde{}}\NormalTok{ speed, }\AttributeTok{data =}\NormalTok{ cars)}
\NormalTok{fit}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}

Call:
lm(formula = dist ~ speed, data = cars)

Coefficients:
(Intercept)        speed  
    -17.579        3.932  
\end{verbatim}

\hypertarget{including-plots}{%
\section{Including Plots}\label{including-plots}}

You can also embed plots. See Figure \ref{fig:pie} for example:

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{par}\NormalTok{(}\AttributeTok{mar =} \FunctionTok{c}\NormalTok{(}\DecValTok{0}\NormalTok{, }\DecValTok{1}\NormalTok{, }\DecValTok{0}\NormalTok{, }\DecValTok{1}\NormalTok{))}
\FunctionTok{pie}\NormalTok{(}
  \FunctionTok{c}\NormalTok{(}\DecValTok{280}\NormalTok{, }\DecValTok{60}\NormalTok{, }\DecValTok{20}\NormalTok{),}
  \FunctionTok{c}\NormalTok{(}\StringTok{\textquotesingle{}Sky\textquotesingle{}}\NormalTok{, }\StringTok{\textquotesingle{}Sunny side of pyramid\textquotesingle{}}\NormalTok{, }\StringTok{\textquotesingle{}Shady side of pyramid\textquotesingle{}}\NormalTok{),}
  \AttributeTok{col =} \FunctionTok{c}\NormalTok{(}\StringTok{\textquotesingle{}\#0292D8\textquotesingle{}}\NormalTok{, }\StringTok{\textquotesingle{}\#F7EA39\textquotesingle{}}\NormalTok{, }\StringTok{\textquotesingle{}\#C4B632\textquotesingle{}}\NormalTok{),}
  \AttributeTok{init.angle =} \SpecialCharTok{{-}}\DecValTok{50}\NormalTok{, }\AttributeTok{border =} \ConstantTok{NA}
\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\begin{figure}
\includegraphics[width=1\linewidth]{Rmarkdown_files/figure-latex/pie-1} \caption{A fancy pie chart.}\label{fig:pie}
\end{figure}

(Credit: Yihui Xie)

\hypertarget{read-in-data-files}{%
\section{Read in data files}\label{read-in-data-files}}

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{simple\_data }\OtherTok{\textless{}{-}} \FunctionTok{read.csv}\NormalTok{(}\StringTok{"https://deepbas.io/data/simple{-}1.dat"}\NormalTok{, )}
\FunctionTok{summary}\NormalTok{(simple\_data) }
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
   initials            state                age      
 Length:3           Length:3           Min.   :45.0  
 Class :character   Class :character   1st Qu.:47.5  
 Mode  :character   Mode  :character   Median :50.0  
                                       Mean   :52.0  
                                       3rd Qu.:55.5  
                                       Max.   :61.0  
     time          
 Length:3          
 Class :character  
 Mode  :character  
                   
                   
                   
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{knitr}\SpecialCharTok{::}\FunctionTok{kable}\NormalTok{(simple\_data)}
\end{Highlighting}
\end{Shaded}

\begin{tabular}{l|l|r|l}
\hline
initials & state & age & time\\
\hline
vib & MA & 61 & 6:01\\
\hline
adc & TX & 45 & 5:45\\
\hline
kme & CT & 50 & 4:19\\
\hline
\end{tabular}

\hypertarget{hide-the-code}{%
\section{Hide the code}\label{hide-the-code}}

If we enter the \texttt{echo\ =\ FALSE} option in the R chunk (see the .Rmd file). This prevents the R code from being printed to your document; you just see the results.

\begin{tabular}{l|l|r|l}
\hline
initials & state & age & time\\
\hline
vib & MA & 61 & 6:01\\
\hline
adc & TX & 45 & 5:45\\
\hline
kme & CT & 50 & 4:19\\
\hline
\end{tabular}

  \bibliography{book.bib,packages.bib}

\end{document}
